function [nextQ,nextq,nextqe,nextdq,nextdQ,nextyf,nextqp]=off_phase(Q,ke,dt,Qy,q,qe,ee,ii)
nextq=q(ii,:);
nextdq=(q(ii,:)-q(ii-1,:))/dt;
nextdQ=nextdq*ke;
nextqe=nextq;
nextqp=nextq-nextqe;
nextQ=ke*nextdq*dt+Q;
nextyf=norm(nextQ)-Qy;
% nextyf(abs(nextyf)<ee)=0;
