function [nextQ,nextq,nextdq,nextdQ,nextQb,nextQa,nextyf,nextqp]=off_phase(q,ke,kp,dt,Qy,Q,Qb,ee,ii)
nextQ=Q(ii,:);
nextdQ=(Q(ii,:)-Q(ii-1,:))/dt;
nextdq=nextdQ/ke;
nextq=(nextdq*dt+q);
nextQb=Qb;
nextqp=nextQb/kp;
nextQa=Q(ii,:);
nextyf=norm(nextQa)-Qy;
% nextyf(abs(nextyf)<ee)=0;
